networks:
  cilantro:
    driver: bridge
    ipam:
      config:
      - gateway: 172.29.5.254
        ip-range: 172.29.5.0/24
        subnet: 172.29.0.0/16
services:
  cilantro:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${LAUNCH_PATH}/docker_files/cilantro
    environment:
    - HOST_IP=172.29.5.0
    - CILANTRO=172.29.5.0
    image: cilantro
    networks:
      cilantro:
        ipv4_address: 172.29.5.0
    volumes:
    - source: ${LOCAL_PATH}/cilantro
      target: /app/
      type: bind
version: '2.3'
