networks:
  cilantro:
    driver: bridge
    ipam:
      config:
      - gateway: 172.29.5.254
        ip-range: 172.29.5.0/24
        subnet: 172.29.0.0/16
services:
  delegate_5:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_delegate
    container_name: delegate_5
    environment:
    - HOST_IP=172.29.5.5
    - SLOT_NUM=0
    - MGMT=172.29.5.255
    - MASTERNODE=172.29.5.0
    - WITNESS=172.29.5.1
    - DELEGATE=172.29.5.5,172.29.5.6,172.29.5.7
    image: cilantro_delegate
    networks:
      cilantro:
        ipv4_address: 172.29.5.5
    volumes:
    - source: ${LOCAL_PATH}/cilantro
      target: /app/
      type: bind
  delegate_6:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_delegate
    container_name: delegate_6
    environment:
    - HOST_IP=172.29.5.6
    - SLOT_NUM=1
    - MGMT=172.29.5.255
    - MASTERNODE=172.29.5.0
    - WITNESS=172.29.5.1
    - DELEGATE=172.29.5.5,172.29.5.6,172.29.5.7
    image: cilantro_delegate
    networks:
      cilantro:
        ipv4_address: 172.29.5.6
    volumes:
    - source: ${LOCAL_PATH}/cilantro
      target: /app/
      type: bind
  delegate_7:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_delegate
    container_name: delegate_7
    environment:
    - HOST_IP=172.29.5.7
    - SLOT_NUM=2
    - MGMT=172.29.5.255
    - MASTERNODE=172.29.5.0
    - WITNESS=172.29.5.1
    - DELEGATE=172.29.5.5,172.29.5.6,172.29.5.7
    image: cilantro_delegate
    networks:
      cilantro:
        ipv4_address: 172.29.5.7
    volumes:
    - source: ${LOCAL_PATH}/cilantro
      target: /app/
      type: bind
  masternode:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_masternode
    container_name: masternode
    environment:
    - HOST_IP=172.29.5.0
    - MGMT=172.29.5.255
    - MASTERNODE=172.29.5.0
    - WITNESS=172.29.5.1
    - DELEGATE=172.29.5.5,172.29.5.6,172.29.5.7
    image: cilantro_masternode
    networks:
      cilantro:
        ipv4_address: 172.29.5.0
    ports:
    - 8080:8080
    volumes:
    - source: ${LOCAL_PATH}/cilantro
      target: /app/
      type: bind
  mgmt:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_base
    container_name: mgmt
    environment:
    - HOST_IP=172.29.5.255
    - MGMT=172.29.5.255
    - MASTERNODE=172.29.5.0
    - WITNESS=172.29.5.1
    - DELEGATE=172.29.5.5,172.29.5.6,172.29.5.7
    image: cilantro_base
    networks:
      cilantro:
        ipv4_address: 172.29.5.255
    stdin_open: true
    tty: true
  witness_1:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_witness
    container_name: witness_1
    environment:
    - HOST_IP=172.29.5.1
    - SLOT_NUM=0
    - MGMT=172.29.5.255
    - MASTERNODE=172.29.5.0
    - WITNESS=172.29.5.1
    - DELEGATE=172.29.5.5,172.29.5.6,172.29.5.7
    image: cilantro_witness
    networks:
      cilantro:
        ipv4_address: 172.29.5.1
    volumes:
    - source: ${LOCAL_PATH}/cilantro
      target: /app/
      type: bind
version: '2.3'
