version: "2.3"
networks:
  vmnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          iprange: 172.28.5.0/24
          gateway: 172.28.5.254

services:
  vmnet_base:
    build:
      context: ${LOCAL_PATH}/vmnet/examples/sample/scripts
      dockerfile: ${DOCKER_DIR}/vmnet_base.dev
    image: vmnet_base.dev
  vmnet_node:
    ip: 172.28.5.x
    image: vmnet_base.dev
    range:
      - 1
      - 5
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/vmnet/examples/sample/scripts
        target: /app/
