networks:
  cilantro:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
          ip-range: 172.29.5.0/24
          gateway: 172.29.5.254
services:
  mgmt:
    ip: 172.29.5.255
  masternode:
    ip: 172.29.5.0
    ports:
      - "8080:8080"
  witness:
    ip: 172.29.5.x
    range:
      - 1
      - 1
  delegate:
    ip: 172.29.5.x
    range:
      - 5
      - 7
