networks:
  cilantro:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
          ip-range: 172.29.5.0/24
          gateway: 172.29.5.254
services:
  cilantro:
    network: cilantro
    ip: 172.29.5.0
