version: "2.3"
services:
  base:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${LAUNCH_PATH}/docker_files/cilantro/cilantro_base
    image: cilantro_base
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/cilantro
        target: /app/
  mgmt:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${LAUNCH_PATH}/docker_files/cilantro/cilantro_base
    image: cilantro_base
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/cilantro
        target: /app/
  masternode:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${LAUNCH_PATH}/docker_files/cilantro/cilantro_masternode
    image: cilantro_masternode
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/cilantro
        target: /app/
  witness:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${LAUNCH_PATH}/docker_files/cilantro/cilantro_witness
    image: cilantro_witness
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/cilantro
        target: /app/
  delegate:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${LAUNCH_PATH}/docker_files/cilantro/cilantro_delegate
    image: cilantro_delegate
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/cilantro
        target: /app/
