version: "2.3"
networks:
  cilantro:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
          ip-range: 172.29.5.0/24
          gateway: 172.29.5.254
services:
  base:
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_base
    image: cilantro_base
    volumes:
      - type: bind
        source: /storage/docker/mysql-datadir
        target: /var/lib/mysql
      - type: bind
        source: ${LOCAL_PATH}/vmnet/logs
        target: /app/logs
  mgmt:
    ip: 172.29.5.255
    stdin_open: true
    tty: true
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_base
    image: cilantro_base
  masternode:
    ip: 172.29.5.0
    ports:
      - "8080:8080"
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_masternode
    image: cilantro_masternode
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/cilantro
        target: /app/
  witness:
    ip: 172.29.5.x
    range:
      - 1
      - 1
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_witness
    image: cilantro_witness
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/cilantro
        target: /app/
  delegate:
    ip: 172.29.5.x
    range:
      - 5
      - 7
    build:
      context: ${LOCAL_PATH}/cilantro
      dockerfile: ${DOCKER_DIR}/cilantro_delegate
    image: cilantro_delegate
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/cilantro
        target: /app/
