version: "2.3"
services:
  vmnet_master:
    build:
      context: ${LOCAL_PATH}/vmnet/scripts
      dockerfile: ${LOCAL_PATH}/vmnet/docker/docker_files/vmnet/vmnet_master
    image: vmnet_master
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/vmnet/scripts
        target: /app/
  vmnet_witness:
    build:
      context: ${LOCAL_PATH}/vmnet/scripts
      dockerfile: ${LOCAL_PATH}/vmnet/docker/docker_files/vmnet/vmnet_witness
    image: vmnet_witness
    volumes:
      - type: bind
        source: ${LOCAL_PATH}/vmnet/scripts
        target: /app/