- name: start nodes
  sudo: yes
  hosts: witnesses
  gather_facts: false

  tasks:
     - name: Remove debug.log
       file:
         state: absent
         path: debug.log
     - name: Start witnesses
       command: python3 /vagrant/scripts/group-client.py